name: C/C++ CI ubuntu-18.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install prerequisites
      run: sudo apt-get install libelf-dev libusb-dev libusb-1.0-0-dev libftdi-dev libftdi1-dev libhidapi-dev texinfo texlive texi2html bison flex
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --enable-doc
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
